// Registration constants
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESSFUL = 'REGISTER_USER_SUCCESSFUL';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

// SignIn constants
export const CHECK_SIGN_IN = 'CHECK_SIGN_IN';
export const SIGN_IN_SUCCESSFUL = 'SIGN_IN_SUCCESSFUL';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

// Forgot password constants
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESSFULL = 'FORGOT_PASSWORD_SUCCESSFULL';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';